module.exports = {
  ALBUM_LIST_FETCH: 'ALBUM_LIST_FETCH',
  ALBUM_LIST_SUCCESS: 'ALBUM_LIST_SUCCESS',
  ALBUM_LIST_FAILURE: 'ALBUM_LIST_FAILURE',
  PHOTO_DETAIL_FETCH: 'PHOTO_DETAIL_FETCH',
  PHOTO_DETAIL_SUCCESS: 'PHOTO_DETAIL_SUCCESS',
  PHOTO_DETAIL_FAILURE: 'PHOTO_DETAIL_FAILURE'
};
