module.exports = {
  ALBUM_LIST_SCREEN_TITLE: 'Albums',
  PHOTO_LIST_SCREEN_DEFAULT_TITLE: 'Photos',
  PHOTO_LIST_COLUMN_COUNT: 3,
  STORAGE_ALBUMS_KEY: 'albumList',
  STORAGE_PHOTO_DETAIL_PREFIX: 'photoId-'
};
